### 배열의 생성

In [363]:
import numpy as np

In [364]:
# 랜덤값으로 배열 생성하기
# np.random.random(배열의 크기)
# 0~1 사이의 값을 가지는 배열을 생성
np.random.rand(2,3)

array([[0.48196566, 0.00526585, 0.52814047],
       [0.93997478, 0.98608355, 0.62887285]])

In [365]:
# 내가 원하는 범위만큼의 랜덤값 생성
# np.random.randint(시작수, 끝수+1, size=배열의크기)
np.random.randint(2,11, size=(2,3))


array([[9, 6, 2],
       [5, 5, 9]])

In [366]:
# 2부터 10까지의 랜덤한 실수값으로 이루어진 (5,4)크기의 배열 생성
# 정수+실수=실수
float=np.random.rand(5,4)
float

array([[7.84865885e-02, 8.17751068e-01, 3.25348477e-01, 7.57117042e-01],
       [8.66076339e-01, 7.79833134e-04, 9.09241276e-01, 5.03007872e-01],
       [1.07078929e-01, 5.33885779e-01, 6.07252135e-01, 2.68385123e-01],
       [6.57350773e-01, 5.08512363e-01, 2.16774195e-01, 6.43503943e-01],
       [6.18252569e-01, 6.86650537e-01, 9.29582148e-01, 3.79421272e-01]])

In [367]:
num=np.random.randint(2,10,size=(5,4))
num

array([[9, 3, 3, 7],
       [3, 2, 8, 2],
       [8, 3, 7, 2],
       [8, 2, 8, 3],
       [7, 2, 3, 3]])

In [368]:
result=num+float
result

array([[9.07848659, 3.81775107, 3.32534848, 7.75711704],
       [3.86607634, 2.00077983, 8.90924128, 2.50300787],
       [8.10707893, 3.53388578, 7.60725213, 2.26838512],
       [8.65735077, 2.50851236, 8.21677419, 3.64350394],
       [7.61825257, 2.68665054, 3.92958215, 3.37942127]])

In [369]:
# 타입 변경하기
# asrtpe(변경할 타입)
float.astype('int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### 배열의 기능

In [370]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [371]:
# 인덱싱
# []
# 2차원에서 0번째 출력
arr[0]

array([1, 2, 3])

In [372]:
arr[0,1]

2

In [373]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [374]:
arr1[3:8]

array([3, 4, 5, 6, 7])

In [375]:
# 0~49 배열 출력

In [376]:
arr2=np.arange(50)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [377]:
# arr2를 (5,10)으로 재 배열하기
# reshape
# 바뀌기 전과 후의 데이터 수가 똑같아야함.
# 출력을 진행하고 저장은 따로 진행하지 않음.
# 저장하고 싶을 시 변수 생성 후 따로 저장해야함.
arr3= arr2.reshape(5,10)

In [378]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [379]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [380]:
# 2차원 슬라이싱
arr3[0:2,0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [381]:
#인덱싱 -> 첫번째 수 :  끝수 +1
# : 끝수+1 = 처음부터 끝수까지
# 시작수 : = 시작수부터 끝까지
# : = 처음부터 끝까지

In [382]:
arr3[:5,0:1]

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

In [383]:
arr3[:4,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [384]:
# 파일 불러오기
data = np.loadtxt("height_weight.txt",delimiter=',')
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [385]:
#bmi 알아보는 문제 
# 키_m = 키_cm/100
# 몸무게 = data[1]
# 몸무게 / (키_m * 키_m )
result=data[1,0:]/((data[0,0:]**2)/10000)
result

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

# Boolean 인덱싱

## True는 출력하고 False는 출력하지 않음

## 인덱싱을 진행할때 값의 개수가 동일한 수의 불리언 데이터 필요

## 원하는 조건에 맞는 값을 출력하는 방법


In [386]:
arr3=np.array([10,20,15,30])
arr3

array([10, 20, 15, 30])

In [387]:
bol = np.array([True,False,True,False])
bol

array([ True, False,  True, False])

In [388]:
arr3[bol]

array([10, 15])

In [389]:
arr3[arr3<17]

array([10, 15])

#arr3 20인 값만 출력

In [390]:
print(arr3==20)
arr3[arr3==20]

[False  True False False]


array([20])

In [391]:
# numpy에서 사용하는 연산 함수

In [392]:
# 1~9까지 랜덤한 정수가 담긴 2,5 크기의 배열 생성.

In [393]:
arr1=np.random.randint(1,10,size=(2,5))
arr1

array([[6, 6, 7, 4, 8],
       [3, 9, 7, 4, 4]])

In [394]:
# 배열 안에 있는 값 더하기
# np.sum (배열값, axis)

In [395]:
np.sum(arr1, axis=1)

array([31, 27])

In [396]:
# 배열 안에 있는 값의 평균
# np,mean(배열값)

In [397]:
np.mean(arr1, axis=1)

array([6.2, 5.4])

## 영화 평점 데이터분석

In [398]:
# 데이터 타입 변경
# dtype
data = np.loadtxt('ratings.txt',delimiter="::", dtype='int')
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [399]:
# 1.전체 평점 구하기
# 2. 각 사용자별 평점 평균 구하기
# 3. 각 사용자별 평균 평점이 4점 이상인 사용자 구하기

In [400]:
# 1. 전체 평점 구하기
np.mean(data[:,2])

3.581564453029317

In [401]:
# 리스트에 [사용자, 사용자의 평균]
# 1번 사용자의 평점 평균 구하기 > 1~6040
#data[:,0] 전체 정보에서 id값만 출력
#전체 정보에서 id값이 1인 값만 출력
user_list=[] #유저의 정보 저장
user=data[data[:,0]==1]
user_list.append( [1, np.mean(user[:,2])])
user_list
# 출력된 값에서 평점값만 추출한후 평균 구하기

[[1, 4.188679245283019]]

In [402]:
# 2. 각 사용자별 평점 평균 구하기

In [403]:
user_list=[]
for i in range(1,6041): #1~6041까지 반복되는 반복문
    user=data[data[:,0]==i] # 반복될때마다 다른 유저(1~6040)의 정보 출력
    user_list.append( [i, np.mean(user[:,2])])
user_list

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

In [404]:
# 3. 각 사용자별 평균 평점이 4점 이상인 사용자 구하기

In [405]:
user_np=np.array(user_list)
user_np

array([[1.00000000e+00, 4.18867925e+00],
       [2.00000000e+00, 3.71317829e+00],
       [3.00000000e+00, 3.90196078e+00],
       ...,
       [6.03800000e+03, 3.80000000e+00],
       [6.03900000e+03, 3.87804878e+00],
       [6.04000000e+03, 3.57771261e+00]])

In [408]:
over4bol=user_np[:,1]>=4

In [410]:
user_np[over4bol,0].astype('int') # 평균 평점이 4점 이상인 사용자의 모든 정보

array([   1,    4,    7, ..., 6027, 6032, 6034])